# Generated by Django 4.0.3 on 2022-03-23 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
