# Generated by Django 4.0.2 on 2022-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_note_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
