# Generated by Django 4.0.3 on 2022-03-23 21:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_note_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
