# Generated by Django 4.0.3 on 2022-03-23 21:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
