# Generated by Django 4.0.3 on 2022-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(default='New Folder', max_length=50),
        ),
    ]
