# Generated by Django 4.0.3 on 2022-03-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_folder_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='public',
        ),
    ]
